version: '2.2'
services:
  api:
    networks:
      # you may set custom IP addresses
      custom_net:
        ipv4_address: 172.34.0.2
    image: video-processing
    build: .
    mem_limit: 2000000000
    cpus: 0.9
    ports:
      - "8003:8003" 

  web-cli:
    networks:
      # you may set custom IP addresses
      custom_net:
        ipv4_address: 172.34.0.3
    image: video-processing
    command: sh

networks:
  # We are creating our own network
  # If we let it create itself and it creates on the 172.24.0.0 subnet,
  # It breaks the connection to WCM (since WCM is on that subnet)
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.34.0.0/16